CREATE TABLE IF NOT EXISTS TRANSACTION_HISTORY(
    ID INT NOT NULL PRIMARY KEY,
    ADDRESS VARCHAR(66) NOT NULL,
    TIMESTAMP INT NOT NULL,
    OPERATION INT NOT NULL,
    EVENT INT NOT NULL,
    TX_HASH VARCHAR(66) NOT NULL,
    TX_BLOCK INT NOT NULL,
    AMOUNT INT NOT NULL,
    EPOCH INT NOT NULL,
    STATUS INT
);

CREATE TABLE IF NOT EXISTS TOTAL_AMOUNT(
    ADDRESS VARCHAR(66) PRIMARY KEY,
    STAKE_AMOUNT INT NOT NULL,
    DELEGATE_AMOUNT INT NOT NULL,
    REWARD_AMOUNT INT NOT NULL
);
