[package]
name = "storage"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocksdb = { version = "0.19", package = "ckb-rocksdb" }
sea-orm = { version = "0.11", features = ["runtime-tokio-native-tls", "sqlx-all"] }
sparse-merkle-tree = { version = "0.6", features = ["trie"] }
