//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "TOTAL_AMOUNT")]
pub struct Model {
    #[sea_orm(column_name = "ADDRESS", primary_key, auto_increment = false)]
    pub address:              String,
    #[sea_orm(column_name = "STAKE_AMOUNT")]
    pub stake_amount:         i64,
    #[sea_orm(column_name = "DELEGATE_AMOUNT")]
    pub delegate_amount:      i64,
    #[sea_orm(column_name = "WITHDRAWABLE_AMOUNT")]
    pub withdrawable_amount:  i64,
    #[sea_orm(column_name = "REWARD_UNLOCK_AMOUNT")]
    pub reward_unlock_amount: i64,
    #[sea_orm(column_name = "REWARD_LOCK_AMOUNT")]
    pub reward_lock_amount:   i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
