//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "TRANSACTION_HISTORY")]
pub struct Model {
    #[sea_orm(column_name = "ID", primary_key, auto_increment = false)]
    pub id:        u64,
    #[sea_orm(column_name = "ADDRESS")]
    pub address:   String,
    #[sea_orm(column_name = "TIMESTAMP")]
    pub timestamp: u64,
    #[sea_orm(column_name = "OPERATION")]
    pub operation: u32,
    #[sea_orm(column_name = "EVENT")]
    pub event:     u32,
    #[sea_orm(column_name = "TX_HASH")]
    pub tx_hash:   String,
    #[sea_orm(column_name = "TX_BLOCK")]
    pub tx_block:  u64,
    #[sea_orm(column_name = "AMOUNT")]
    pub amount:    i64,
    #[sea_orm(column_name = "EPOCH")]
    pub epoch:     u64,
    #[sea_orm(column_name = "STATUS")]
    pub status:    Option<u32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
